name: Release new version
on:
  workflow_dispatch:

jobs:
  clojure:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install babashka
        uses: just-sultanov/setup-babashka@v2
        with:
          version: '1.4.192'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Babashka version
        run: bb --version

      - name: Run tests
        run: echo "testing..."

      - name: Release
        run: bb run release

      - name: Commit version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: resources/VERSION

      - name: Deploy
        run: echo "deploying..."
